name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: electron-mocha
  IMAGE_VERSION: '16'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - name: Run dos2unix
        working-directory: ${{ env.IMAGE_VERSION }}
        run: |
          sudo apt-get update
          sudo apt-get -y install dos2unix
          dos2unix docker-entrypoint.sh Dockerfile
          sudo chmod +x docker-entrypoint.sh
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
        working-directory: ${{ env.IMAGE_VERSION }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Push image
        working-directory: ${{ env.IMAGE_VERSION }}
        run: |
          IMAGE_ID=$REGISTRY/${{ github.repository }
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_VERSION
          docker push $IMAGE_ID:$IMAGE_VERSION
